### ISSUE TITLE
Allow the client to specify the template to use

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#16]
Allow clients to specify which template should be used to create the model, bypassing the BLAST search done at the beginning.

This is required for issue https://github.com/cmbi/hope-flask/issues/303 in HOPE. Coos posted the following comment in that discussion:

>Right now hommod's organizes models by naming them after their input sequence, species and covered range. If hommod is to take a template id as input, the model storage system would have to change, because there would be an extra parameter. There can then be two different models for the same piece of protein, differing by template only.

...and...

>Hommod blasts for a template by itself, it forces yasara to use the found template. Yes, it's possible to tell yasara which template it should take!

We need to discuss what changes would need to be made to the storage system.

**Comment by cbaakman** [comment]
https://github.com/cmbi/hommod-rest/commit/df2fc606d88a3196acd7e7fb214c51922a2f144b adds this option. The post request now has an optional argument 'template_id'. An example value for this can be: "1crn_A"
