### ISSUE TITLE
How should the result be returned

### ISSUE THREAD

**Issue by cbaakman** [cmbi/hommod-rest#2]
Currently the result is a json formatted response containing:

* Alignment sequences
* PDB file content
* Information such as the template

This response is quite large. Is it better to just return the zipped model result? Is there a another option?

**Comment by jonblack** [comment]
Can you post an example of the response here? Don't put the entire PDB file content, just show where that comes - I'm more interested in the structure and keys.

**Comment by cbaakman** [comment]
I believe this has already changed in https://github.com/cmbi/hommod-rest/commit/66d0a18c92499e04a630ba8fcccb9a9a2c41e8a7

**Comment by jonblack** [comment]
Great.
