### ISSUE TITLE
Pass configuration to services

### ISSUE THREAD

**Issue by jonblack** [cmbi/hommod-rest#27]
When a service requires settings, pass them in the constructor rather than importing the flask app where it's not needed.

`SecStrProvider` is an example of a service with this problem. There may be others.

**Comment by cbaakman** [comment]
Could you give a more detailed example of how this should be done. (maybe in hope)
I need to know:
* where is the config setting imported? It is the create_app function? How about tests?
* how do functions that require the service aqcuire a pointer to the service? Should I make a new service object at multiple locations in hommod?

**Comment by jonblack** [comment]
>Where is the config setting imported? It is the create_app function? How about tests?

Configuration settings should indeed be loaded in the `create_app` function in `factory.py`. See HOPE for an example. In this function you import the service instance from `secstr.py` and set the member variables from the settings (`yasara_dir` and `dssp_dir`).

>how do functions that require the service aqcuire a pointer to the service? Should I make a new service object at multiple locations in hommod?

There are no such things as pointers in Python. Everything is a reference to an object. In `secstr` at the bottom we create the instance of the service. Wherever we import that instance, we can use it. We just have to make sure we configure it first, which is what happens in `create_app`. So you don't need to create it anywhere, since it's already been created in `secstr`.

**Comment by cbaakman** [comment]
Fixed in https://github.com/cmbi/hommod-rest/commit/55b0b8c523f8d76c8d5ff27fa0e442c0846469cb
